### ISSUE TITLE
Help with XADES-EPES signature from .p12 cert

### ISSUE THREAD

**Issue by jsousa-Resulto** [PeculiarVentures/xadesjs#122]
Hi! At first thanks for your great work! This repo is amazing.
I'm trying to use it for signing a file with a .p12 cert, i've read related issues like https://github.com/PeculiarVentures/xadesjs/issues/54 but without success... When I get the signature from xadesjs it differs about official software of signatures, and i don't know how i can make some parts, for example:

- xadesjs:

`            <ds:X509Data>
<ds:X509Certificate>MIII1TCCB72...</ds:X509Certificate>
            </ds:X509Data>`

- official software:
`<ds:X509Data>
                <ds:X509Certificate>MIII1TCCB72gA...</ds:X509Certificate>
                <ds:X509Certificate>MIIG3DCCBMSg...</ds:X509Certificate>
                <ds:X509Certificate>MIIFgzCCA2ugAw...</ds:X509Certificate>
            </ds:X509Data>`

I can provide the both files if you need.

I'm obtaining the private key as you explained in https://github.com/PeculiarVentures/xadesjs/issues/78 and https://github.com/PeculiarVentures/xadesjs/issues/107 but i don't understand some things, like what information should be setted into "signingCertificate"? PublicCert? Because when i set this, I get errors running the app.. I'm sure i'm doing something wrong.. I would be very appreciated if you can support me with an example consuming a p12 and using their public cert to sign the file with XADES-EPES

Thanks in advance!

**Comment by microshine** [comment]
> official software:
<ds:X509Data> <ds:X509Certificate>MIII1TCCB72gA...</ds:X509Certificate> <ds:X509Certificate>MIIG3DCCBMSg...</ds:X509Certificate> <ds:X509Certificate>MIIFgzCCA2ugAw...</ds:X509Certificate> </ds:X509Data>

Looks like your `X509Data` contains the certificate chain (leaf + issuer CA + ... + issuer CA)

> I'm obtaining the private key as you explained

Do you have the private key in PKCS#8 format?

XAdESjs supports WebCrypto API which supports PKCS#8 key importing. And you can use `crypto.subtle.importKey` to create a private `CryptoKey`

If you don't, you can use [PKCS#12 pkijs example](https://github.com/PeculiarVentures/PKI.js/blob/54966e88bf4014d791646a986879f4d2336235b0/examples/PKCS12SimpleExample/es6.ts#L56-L75) to get `Certificate` and `CryptoKey`

> what information should be setted into "signingCertificate"? PublicCert? Because when i set this, I get errors running the app

What is your error?

**Comment by jsousa-Resulto** [comment]
> Looks like your `X509Data` contains the certificate chain (leaf + issuer CA + ... + issuer CA)

Yes but how can I add this info to xadesjs? I've tried to get the public chain and add them to X509 array but xadesjs generate the file with format:  
<ds:X509Data> <ds:X509Certificate>MIII1TCCB72...</ds:X509Certificate> </ds:X509Data>
<ds:X509Data> <ds:X509Certificate>MIIG3DCCBMSg...</ds:X509Certificate> </ds:X509Data>
<ds:X509Data> <ds:X509Certificate> MIIFgzCCA2ugAw...</ds:X509Certificate> </ds:X509Data>

Separating X509Data tags by each member of array...

> Do you have the private key in PKCS#8 format?

I think so, I'm getting and converting in PKCS8 like: https://codesandbox.io/s/xadesjs-issue-78-o00ez?file=/index.js

> What is your error?

Sorry, I was wrong, The error was related with trying to set my public pem string to keyValue property (inside options in sign function). Could you please how I should convert my public cert into CryptoKey for using in keyValue?

Thanks a lot for your help!

**Comment by microshine** [comment]
> Yes but how can I add this info to xadesjs?

Do it via XML structure of `signedXml.XmlSignature` object.

```js
import * as XmlDSig from "xmldsigjs";

const x509Data = new XmlDSig.KeyInfoX509Data();
x509Data.AddCertificate(new XmlDSig.X509Certificate(Buffer.from(cert, "base64")));
x509Data.AddCertificate(new XmlDSig.X509Certificate(Buffer.from(cert2, "base64")));
signedXml.XmlSignature.KeyInfo.Add(x509Data);

const signature = await signedXml.Sign(
  // ...
```

__Console log__
```xml
<ds:KeyInfo>
  <ds:X509Data>
    <ds:X509Certificate>MIIGgTCC...fPasd9NbpBNp7A==</ds:X509Certificate>
    <ds:X509Certificate>MIIGgTCC...fPasd9NbpBNp7A==</ds:X509Certificate>
  </ds:X509Data>
</ds:KeyInfo>
```

**Comment by jsousa-Resulto** [comment]
Thanks @microshine for your help, now the format of my x509Data is well formed. 
Now I'm just trying to validate the result but if I paste my signed xml in xadesjs.com error appears:
`XMLJS0013: Cryptographic error: Invalid digest for uri 'undefined'. Calculated digest is zaj2/SKHHWrsxj8ONry2K4auOakwC7FxMA6DmTBJyUY= but the xml to validate supplies digest lWj7TIL2nSX41JjdGeGDeX34HoYXCW8VqpTvnWLoCNQ=`

This error is related with SignedInfo -> First Reference block:
`<ds:SignedInfo>
            <ds:CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
            <ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
            <ds:Reference>
                <ds:Transforms>
                    <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
                </ds:Transforms>
                <ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
                <ds:DigestValue>lWj7TIL2nSX41JjdGeGDeX34HoYXCW8VqpTvnWLoCNQ=</ds:DigestValue>
            </ds:Reference>
            <ds:Reference URI="#xades-id-b87fc0df3c99" Type="http://uri.etsi.org/01903#SignedProperties">
                <ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
                <ds:DigestValue>/Tjd4XjWBOkxsbLGYiXVIQjFQmU=</ds:DigestValue>
            </ds:Reference>
        </ds:SignedInfo>`

Could you please help me to understand what is causing the error?

Thanks in advance!

**Comment by jsousa-Resulto** [comment]
Hi guys, any idea what can cause this digest calculation error? Maybe could be related with canonicalization?
I've tried to add c14n to transforms, adding Id and Type to references, adding '' to URI for avoiding "undefined"... but the error should be related with other section..

My code is published in: https://codesandbox.io/s/p12-xades-rslt-3j7l5e

Your help would be very very appreciate.

Thanks a lot!

**Comment by microshine** [comment]
Could you share your signed XML file (microshine@mail.ru)?

**Comment by jsousa-Resulto** [comment]
Sent! 

Thanks a lot!

**Comment by microshine** [comment]
I found the problem in your example. You are using incorrect `uri` attribute for `KeyInfo` reference. If you need to point to Id it must be the next format `#<id>`

try to update your example and try again
```diff
- { uri: signedXml.XmlSignature.KeyInfo.Id, hash }
+ { uri: `#${signedXml.XmlSignature.KeyInfo.Id}`, hash }
```

Here is my sign example without PFX but with X509 chain generator.

__TypeScript__
```ts
import * as fs from "fs";
import * as crypto from "crypto";
import * as xades from "xadesjs";
import * as xmldsig from "xmldsigjs";
import * as x509 from "@peculiar/x509";
import { Convert } from "pvtsutils";

const nodeCrypto = crypto.webcrypto as unknown as Crypto;
xades.Application.setEngine("NodeJS", nodeCrypto);
x509.cryptoProvider.set(nodeCrypto);

const hash = "SHA-256";
const alg: EcKeyGenParams & EcdsaParams = {
  name: "ECDSA",
  namedCurve: "P-256",
  hash,
};

async function createCert() {
  const currentDate = new Date();;
  const rootKeys = await nodeCrypto.subtle.generateKey(alg, false, ["sign", "verify"]);
  const rootCert = await x509.X509CertificateGenerator.createSelfSigned({
    serialNumber: Convert.ToHex(nodeCrypto.getRandomValues(new Uint8Array(10))),
    name: "CN=Root CA",
    keys: rootKeys,
    notBefore: currentDate,
    notAfter: new Date(currentDate.getTime() + 172800000),
    signingAlgorithm: alg,
  });
  rootCert.privateKey = rootKeys.privateKey;

  const leafKeys = await nodeCrypto.subtle.generateKey(alg, false, ["sign", "verify"]);
  const leafCert = await x509.X509CertificateGenerator.create({
    serialNumber: Convert.ToHex(nodeCrypto.getRandomValues(new Uint8Array(10))),
    subject: "CN=Leaf cert",
    issuer: rootCert.subjectName,
    publicKey: leafKeys.publicKey,
    notBefore: currentDate,
    notAfter: new Date(currentDate.getTime() + 86400000),
    signingKey: rootKeys.privateKey,
    signingAlgorithm: alg,
  });
  leafCert.privateKey = leafKeys.privateKey;

  return new x509.X509Certificates([leafCert, rootCert]);
}

async function main() {
  const xmlString = fs.readFileSync("invoice.xml", "utf-8");
  const xmlDoc = xades.Parse(xmlString);
  const chain = await createCert();

  // new instance of signed document
  const signedXml = new xades.SignedXml();

  // adding of public chain into x509Data block of KeyInfo
  const x509Data = new xmldsig.KeyInfoX509Data();
  for (const cert of chain) {
    x509Data.AddCertificate(new xmldsig.X509Certificate(cert.rawData));
  }
  signedXml.XmlSignature.KeyInfo.Id =
    signedXml.XmlSignature.Id + "-KeyInfo";
  signedXml.XmlSignature.KeyInfo.Add(x509Data);

  // Sign
  const signature = await signedXml.Sign(
    // Signing document
    alg, // algorithm
    chain[0].privateKey!, // key
    xmlDoc, // document
    {
      // options
      references: [
        {
          uri: "",
          hash,
          transforms: ["enveloped"],
          type: "http://www.w3.org/2000/09/xmldsig#Object",
          id: signedXml.XmlSignature.Id + "-Reference"
        },
        { uri: `#${signedXml.XmlSignature.KeyInfo.Id}`, hash }
      ],
      policy: {
        hash,
        identifier: {
          value:
            "http://www.facturae.es/politica_de_firma_formato_facturae/politica_de_firma_formato_facturae_v3_1.pdf"
        },
        // description: "Política de firma electrónica para facturación electrónica con formato Facturae"
      },
      productionPlace: {
        country: "Spain",
        state: "Badajoz",
        city: "Merida",
        code: "06800"
      },
      keyValue: await chain[0].publicKey.export(),
      signingTime: {
        value: new Date(),
      },
      signerRole: { claimed: ["emisor"] },
      signingCertificate: chain[0].toString("base64"),
    }
  );

  xmlDoc.documentElement.appendChild(signature.GetXml()!);
  fs.writeFileSync(
    "signed.xml",
    signedXml.toString()
  );
}

main().catch(e => {
  console.error();
  process.exit(1);
});
```

NOTE: If you are using VSCode please enable TS for type validation (use  `// @ts-check`). Your code has some type errors, and I fixed them in my example.

Here is a good article about JS in VSCode https://code.visualstudio.com/docs/nodejs/working-with-javascript.

**Comment by jsousa-Resulto** [comment]
Thanks a lot @microshine for your appreciation about id and your notes. Unfortunately my error persist:

XMLJS0013: Cryptographic error: Invalid digest for uri ''. 
Calculated digest is Vk0v+zDRD5ksRIIvGM2kWprsuuziCrBDV+Do1edDh3Q= but the xml to validate supplies digest lWj7TIL2nSX41JjdGeGDeX34HoYXCW8VqpTvnWLoCNQ=

Based on your code I think the problem is related with use of privateKey and publicKey when signedXml.Sign is called.

I'm going to continue testing and looking for a solution.

Thanks

**Comment by microshine** [comment]
@jsousa-Resulto Please code I've shared it works without `XMLJS0013` error. 

The problem can be in XML serialization. Maybe something changes your output XML. Please try to serialize XML like I do in my example

```js
  xmlDoc.documentElement.appendChild(signature.GetXml()!);
  fs.writeFileSync(
    "signed.xml",
    signedXml.toString()
  );
```

**Comment by jsousa-Resulto** [comment]
> Please code I've shared it works without `XMLJS0013` error.

Of course I know it! 

But I've adapted my code (published) to run like yours (with some differences but same serialization) and result has been the same: XMLJS0013 error. 

By that I've thought my error is related with other reason :( 

I've tried to use crypto like you but I got the error: Unsupported key usage for an RSASSA-PKCS1-v1_5 key
(same result with some algorithms)

I'm reading if the algorithms can be part of the problem buy I've no idea..

Thanks a lot for your support

**Comment by microshine** [comment]
Please send me the last signed file. I'd like to understand which reference is broken

**Comment by jsousa-Resulto** [comment]
Hi @microshine, comparing with other signed files I've found a missing block:

                <xades:SignedDataObjectProperties>
                    <xades:DataObjectFormat ObjectReference="#Reference-cd1bd792-4bac-49a6-b0a3-6082ee520e8b">
                        <xades:Description/>
                        <xades:ObjectIdentifier>
                            <xades:Identifier Qualifier="OIDAsURN">urn:oid:1.2.840.10003.5.109.10</xades:Identifier>
                            <xades:Description/>
                        </xades:ObjectIdentifier>
                        <xades:MimeType>text/xml</xades:MimeType>
                        <xades:Encoding/>
                    </xades:DataObjectFormat>
                </xades:SignedDataObjectProperties>

The ObjectReference is referenced to the "corrupt" reference block.

How cain I add this SignedDataObjectProperties to signedXML with xmldsigjs o xadesjs? I'm reading documentation to find how do it but if you can guide me it would be faster.

Thanks a lot and I hope be closer than solution...

**Comment by microshine** [comment]
Please call this code before the `Sign` method

```js
const dataObjectFormat = new xades.xml.DataObjectFormat();
dataObjectFormat.ObjectReference = "#Reference-cd1bd792-4bac-49a6-b0a3-6082ee520e8b";
dataObjectFormat.Description = "Política de firma electrónica para facturación electrónica con formato Facturae";
dataObjectFormat.ObjectIdentifier.Identifier.Qualifier = "OIDAsURN";
dataObjectFormat.ObjectIdentifier.Identifier.Value = "urn:oid:1.2.840.10003.5.109.10";
dataObjectFormat.MimeType = "text/xml";
signedXml.SignedProperties.SignedDataObjectProperties.DataObjectFormats.Add(dataObjectFormat);
```

**Comment by microshine** [comment]
https://codesandbox.io/s/issue-122-xfjb6v?file=/src/index.ts

Please see this app

__Run__
```
npx ts-node src
```

__Output__
```
Application started
true
```

**Comment by microshine** [comment]
It's not clear why you've got `reference` error. I bet it's not the problem in key usage, it could be the problem in `canon` method or xml serialization. But you can see that my scripts works, and I can't reproduce your exception

There is one more way how to catch the difference. You can edit the `DigestReference` method directly in `node_modules/xmldsigjs/build` folder https://github.com/PeculiarVentures/xmldsigjs/blob/master/src/signed_xml.ts#L436. And add `console.log(canonOutput)` to see it on signing and verification

**Comment by jsousa-Resulto** [comment]
Hi @microshine you was right (I had no doubts about that!), I've minified my input xml and error in Reference dissapears. Now the same error is in next reference (KeyInfo)... Commenting reference of KeyInfo, I got a valid signature ( :,) ), but with the block of KeyInfo added:
`XMLJS0013: Cryptographic error: Invalid digest for uri '#id-ec6970bc8ed9-KeyInfo'. Calculated digest is tgergis9k2YmPCE9ptZf2IG6eZ1y+zy9fEAPspatifQ= but the xml to validate supplies digest 3daHnrGmHOEX3Jsos+atKFI836DQB7qO1BGTm+pzmbw=`

The canon output looks great (I think so...):
`<ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:f="http://www.facturae.es/Facturae/2009/v3.2/Facturae" Id="id-ec6970bc8ed9-KeyInfo"><ds:X509Data><ds:X509Certificate>MIII1TCCB72gAwIBAgIQcYa5BlaqQcJgWwumzY76ezANBgkqhkiG9w0BAQsFADBNMQswCQYDVQQGEwJFUzERMA8GA1UECgwIRk5NVC1SQ00xDjAMBgNVBAsMBUNFUkVTMRswGQYDVQQDDBJBQyBSZXByZXNlbnRhY2nDs24wHhcNMjEwMzI0MDk1MTM0WhcNMjMwMzI0MDk1MTM0WjCCARcxVzBVBgNVBA0MTlJlZzowNjAxNyAvSG9qYTpCQS0yNzc2NSAvVG9tbzo2NDkgL0ZvbGlvOjM3IC9GZWNoYToyMS8wMS8yMDIxIC9JbnNjcmlwY2nDs246MzEYMBYGA1UEBRMPSURDRVMtMDg4ODk4MzBQMQ4wDAYDVQQqDAVKT1JHRTEZMBcGA1UEBAwQU09VU0EgVklMTEFGQUlOQTEtMCsGA1UEAwwkMDg4ODk4MzBQIEpPUkdFIFNPVVNBIChSOiBCMDY3MDU3MzUpMRgwFgYDVQRhDA9WQVRFUy1CMDY3MDU3MzUxITAfBgNVBAoMGFJFU1VMVE8gQ09OU1VMVE9SSUEgUy5MLjELMAkGA1UEBhMCRVMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCaRSGpYC6EsNWbVpCkvGB7Kjpl7Osk3mrJNBkVX3AczPIv9w4vkdPxYK6bG3yhMmXI1ElkJnhyV++c9/Zv92epL5ITRBawDxYknmsyBpInSd2xXPMy2CxWGl47ms/hkW51EqsOUfN/A0/q2OnBmdZ2PIGEy6tWqDq/VtRvh99NQnMJinZ+U4UzZC+wMofvIo2dTvXw8jfhynx1aBFapu2/9+Qi4WFIhT+uUpq18CGaZadBBaSSaz4bYAMzsE0WEbrz307L38FoReMFSbySfkoyHzDDkI3ZFhmk0SUZMyq3+Zj6wCFRk6/oHc66+/7SowFhzy16hC3Ecc2XZRxsGYvLAgMBAAGjggTjMIIE3zCCAQkGA1UdEQSCAQAwgf2BHUpTT1VTQUBSRVNVTFRPQ09OU1VMVE9SSUEuQ09NpIHbMIHYMSYwJAYJKwYBBAGsZgEUDBdBZG1pbmlzdHJhZG9yIHNvbGlkYXJpbzEeMBwGCSsGAQQBrGYBBwwPVkFURVMtQjA2NzA1NzM1MScwJQYJKwYBBAGsZgEGDBhSRVNVTFRPIENPTlNVTFRPUklBIFMuTC4xHjAcBgkrBgEEAaxmAQQMD0lEQ0VTLTA4ODg5ODMwUDEZMBcGCSsGAQQBrGYBAwwKVklMTEFGQUlOQTEUMBIGCSsGAQQBrGYBAgwFU09VU0ExFDASBgkrBgEEAaxmAQEMBUpPUkdFMAwGA1UdEwEB/wQCMAAwDgYDVR0PAQH/BAQDAgXgMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDBDCBggYIKwYBBQUHAQEEdjB0MD0GCCsGAQUFBzABhjFodHRwOi8vb2NzcHJlcC5jZXJ0LmZubXQuZXMvb2NzcHJlcC9PY3NwUmVzcG9uZGVyMDMGCCsGAQUFBzAChidodHRwOi8vd3d3LmNlcnQuZm5tdC5lcy9jZXJ0cy9BQ1JFUC5jcnQwHQYDVR0OBBYEFMJuhlrxwuzaA/rClqXWRnBMkkGsMIIBPwYDVR0gBIIBNjCCATIwggEYBgorBgEEAaxmAwsBMIIBCDApBggrBgEFBQcCARYdaHR0cDovL3d3dy5jZXJ0LmZubXQuZXMvZHBjcy8wgdoGCCsGAQUFBwICMIHNDIHKQ2VydGlmaWNhZG8gY3VhbGlmaWNhZG8gZGUgcmVwcmVzZW50YW50ZSBkZSBwLiBqdXLDrWRpY2EgKHJlbGFjacOzbiBjb24gQUFQUCB5IGNvbnRyYXRhY2nDs24pLiBTdWpldG8gYSBjb25kaWNpb25lcyBkZSB1c28gc2Vnw7puIERQQyBkZSBGTk1ULVJDTSwgTklGOiBRMjgyNjAwNC1KIChDL0pvcmdlIEp1YW4gMTA2LTI4MDA5LU1hZHJpZC1Fc3Bhw7FhKTAJBgcEAIvsQAEAMAkGB2CFVAEDBQgwgaYGCCsGAQUFBwEDBIGZMIGWMAgGBgQAjkYBATATBgYEAI5GAQYwCQYHBACORgEGATBoBgYEAI5GAQUwXjAtFidodHRwczovL3d3dy5jZXJ0LmZubXQuZXMvcGRzL1BEU19lcy5wZGYTAmVzMC0WJ2h0dHBzOi8vd3d3LmNlcnQuZm5tdC5lcy9wZHMvUERTX2VuLnBkZhMCZW4wCwYGBACORgEDAgEPMB8GA1UdIwQYMBaAFNxQlp/XMYnJEeTvll/2X4JSRmJTMIHhBgNVHR8EgdkwgdYwgdOggdCggc2GgZ1sZGFwOi8vbGRhcHJlcC5jZXJ0LmZubXQuZXMvQ049Q1JMMTMzOSxPVT1BQyUyMFJlcHJlc2VudGFjaW9uLE9VPUNFUkVTLE89Rk5NVC1SQ00sQz1FUz9jZXJ0aWZpY2F0ZVJldm9jYXRpb25MaXN0O2JpbmFyeT9iYXNlP29iamVjdGNsYXNzPWNSTERpc3RyaWJ1dGlvblBvaW50hitodHRwOi8vd3d3LmNlcnQuZm5tdC5lcy9jcmxzcmVwL0NSTDEzMzkuY3JsMA0GCSqGSIb3DQEBCwUAA4IBAQBJhKNfXCJujKV/Pf81axSCKetzQ3hFqvoy0Jh4lAJmzj/Jn5cDRjN3J1/Aa2TAwn0EMy67LCl8w4oLVdaW6Omp3fHcYqI0XLKQD9ZSqaEsaw2QjpAV5Hw5d7/CMdgmHPAxqbc6F4HDuqqeLbAWMe/wSmGxWEIZIWIJ7T868EGuALUafGwe+4zhB6FszF1XEstEnfSJ1dgsjfw8gp2dVglRPcbCMOWpjWGaLTk7FxlYI+QY+04BKxIy5Gv1upfZECWoUvhXU6eNujBmSbaeu/3cEjYmW52iFRF3iHtRgORXAnqh9U9QP8uQOpQ2ovoim+3Y2Ef2jfb5uSeH0LcHd1CX</ds:X509Certificate><ds:X509Certificate>MIIG3DCCBMSgAwIBAgIQYcLU1PaprndVkma5ja/WITANBgkqhkiG9w0BAQsFADA7MQswCQYDVQQGEwJFUzERMA8GA1UECgwIRk5NVC1SQ00xGTAXBgNVBAsMEEFDIFJBSVogRk5NVC1SQ00wHhcNMTUwNjMwMDk1MTUzWhcNMjkxMjMxMTA1MTUzWjBNMQswCQYDVQQGEwJFUzERMA8GA1UECgwIRk5NVC1SQ00xDjAMBgNVBAsMBUNFUkVTMRswGQYDVQQDDBJBQyBSZXByZXNlbnRhY2nDs24wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDCO7E+oUYbuTJaWkEQtIFgcRHD/kHavy+XBFdfCdUzDh9w7Yq4kYckBPW/YU1QRa4v35HbajEMCs4cyLnoJy8Wyzq7qrSwmNHhMYDjtGywJXbCo5SZVbIwyagWig8Nb/x9Y5WGWIY76E9agPAoEYOxOG8h1J6ipNoBbq0R+4N4ODaq57ABY7mUSXb4WgjoVg4WxxZw0GGLuc8R1idoX1G/VqxvNymeCZ7o1bEwbs7X3NhRsK21w3ju8pkUNZXN6Pkflh9qIslOLiokKbiDwwAZE4nvU//B8Q8FLYk1sgTQTLET2EQZ308FlECRp3i6Ay4iezc0Yd3FKIDmOxCdDUcDAgMBAAGjggLIMIICxDASBgNVHRMBAf8ECDAGAQH/AgEAMA4GA1UdDwEB/wQEAwIBBjAdBgNVHQ4EFgQU3FCWn9cxickR5O+WX/ZfglJGYlMwgZgGCCsGAQUFBwEBBIGLMIGIMEkGCCsGAQUFBzABhj1odHRwOi8vb2NzcGZubXRyY21jYS5jZXJ0LmZubXQuZXMvb2NzcGZubXRyY21jYS9PY3NwUmVzcG9uZGVyMDsGCCsGAQUFBzAChi9odHRwOi8vd3d3LmNlcnQuZm5tdC5lcy9jZXJ0cy9BQ1JBSVpGTk1UUkNNLmNydDAfBgNVHSMEGDAWgBT3fcX9xOiaG3dkp/UdoMy/h2CabTCB6wYDVR0gBIHjMIHgMIHdBgRVHSAAMIHUMCkGCCsGAQUFBwIBFh1odHRwOi8vd3d3LmNlcnQuZm5tdC5lcy9kcGNzLzCBpgYIKwYBBQUHAgIwgZkMgZZTdWpldG8gYSBsYXMgY29uZGljaW9uZXMgZGUgdXNvIGV4cHVlc3RhcyBlbiBsYSBEZWNsYXJhY2nDs24gZGUgUHLDoWN0aWNhcyBkZSBDZXJ0aWZpY2FjacOzbiBkZSBsYSBGTk1ULVJDTSAoIEMvIEpvcmdlIEp1YW4sIDEwNi0yODAwOS1NYWRyaWQtRXNwYcOxYSkwgdQGA1UdHwSBzDCByTCBxqCBw6CBwIaBkGxkYXA6Ly9sZGFwZm5tdC5jZXJ0LmZubXQuZXMvQ049Q1JMLE9VPUFDJTIwUkFJWiUyMEZOTVQtUkNNLE89Rk5NVC1SQ00sQz1FUz9hdXRob3JpdHlSZXZvY2F0aW9uTGlzdDtiaW5hcnk/YmFzZT9vYmplY3RjbGFzcz1jUkxEaXN0cmlidXRpb25Qb2ludIYraHR0cDovL3d3dy5jZXJ0LmZubXQuZXMvY3Jscy9BUkxGTk1UUkNNLmNybDANBgkqhkiG9w0BAQsFAAOCAgEApS/HpvFq3S42VmjXtoNVxdh+m1/NdjoWVY6M2o9c+UZofrZWbaiQ+aNOn6/+Qf/LZk41jD+nEa/O1GkPyAineYtjyW6Ae7ltVPIVIWQa3fALcgyN7s/U31qPooU7Zv7a5mghpxapWHvtL9yxpLjrtGsZD32qysIJ2pjDqJa5WeWVKF2RS1zy6Bm/9JzlxzTCH03kivP5ltp+cHik/KzJZ+HgPv6BLwO+OYrJ19vGbPuDGgOj7uJTG3XQIlZchTltgCmNRPKs/HOGOyDmWxm07FmrADQ1NWag3gjoH8xcfAlp9aBnm/UXFJuAkGOq8ASr+A5dpJeDP/rlKphDdxJpG5YKRwRSb7PnAccstmGxynL+K/0ofxAhbWqC6z7KeGyZBTeVIilPhp+xZzJnvFVBjN6s2j7W3+esQkiT4SdY9RN+c3tBuWF54UNc7YVe6KVTjzkpev9szp6vUNQ+A45i2KGXRLN6/16nA9fujzITRWmX4tOGABo0aL/wBrf3Po89gvZwZRaVQ9Bw/KfEF8eZDhA1MgQKSPJLSXSl58elHGFLUR2CQMGl+mgfPB0qZUUkRG/RYpZLocczAz6pfkxA3Mt3DfIyVtA/YJ0O4ZYpdbH9zdJZI1RQEWmFrMOrEAWmGIG0SmNpARqOPJsTQJomUcvd3EvA7so2LzLJ+Sjj2So=</ds:X509Certificate><ds:X509Certificate>MIIFgzCCA2ugAwIBAgIPXZONMGc2yAYdGsdUhGkHMA0GCSqGSIb3DQEBCwUAMDsxCzAJBgNVBAYTAkVTMREwDwYDVQQKDAhGTk1ULVJDTTEZMBcGA1UECwwQQUMgUkFJWiBGTk1ULVJDTTAeFw0wODEwMjkxNTU5NTZaFw0zMDAxMDEwMDAwMDBaMDsxCzAJBgNVBAYTAkVTMREwDwYDVQQKDAhGTk1ULVJDTTEZMBcGA1UECwwQQUMgUkFJWiBGTk1ULVJDTTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBALpxgHpMhm5/yBNtwMZ9HACXjywMI7sQmkCpGreHiPibVmr75nuOi5KOpyVdWRHbNi63URcfqQgfBBckWKo3Shjf5TnUV/3XwSyRAZHiItQDwFj8d0fsjz50Q7qsNI1NOHZnjrDIbzAzWHFctPVrbtQBULgTfmxKo0nRIBnuvMApGGWn3v7v3QqQIecaZ5JCEJhfTzC8PhxFtBDXaEAUwED653cXeuYLj2VbPNmaUtu1vZ5Gzz3rkQUCwJaydkxNEJY7kvqcfw+Z374jNUUeAlz+taibmSXaXvMiwzn15Cou08YfxGyqxRxqAQVKL9LFwag0Jl1mpdICIfkYtwb1TplvqKtMUejPUBjFd8g5CSxJkjKZqLsXF3mwWsXmo8RZZUc1g16p6DULmbvkzSDGm0oGObVo/CK67lWMK07q87Hj/LaZmtVC+nFNCM+HHmpxffnTtOmlcYF7wk5HlqX2doWjKI/pgG6BU6VtX7hI+cL5NqYuSf+4lsKMB7ObiFj86xsc3i1w4peSMKGJ47xVqCfWS+2QrYv6YyVZLag13cqXM7zlzced0ezvXg5KkAYmY6252TUtB7p2ZSysV4999AeU14ECll2jB0nVetBX+RvnU0Z1qrB5QstocQjpYL05ac70r8NWQMetUqIJ5G+GR4of6ygnXYMgrwTJbFaai0b1AgMBAAGjgYMwgYAwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAQYwHQYDVR0OBBYEFPd9xf3E6Jobd2Sn9R2gzL+HYJptMD4GA1UdIAQ3MDUwMwYEVR0gADArMCkGCCsGAQUFBwIBFh1odHRwOi8vd3d3LmNlcnQuZm5tdC5lcy9kcGNzLzANBgkqhkiG9w0BAQsFAAOCAgEAB5BK3/MjTvDDnFFlm5wioooMhfNzKWtN/gHiqQxjAb8EZ6WdmF/9ARP67Jpi6Yb+tmLSbkyU+8B1RXxlDPiyN8+sD8+Nb/kZ94/sHvJwnvDKuO+3/3Y3dlv2bojzr2IyIpMNOmqOFGYMLVN0V2Ue1bLdI4E7pWYjJ2cJj+F3qkPNZVEI7VFY/uY5+ctHhKQV8Xa7pO6kO8Rf77IzlhEYt8llvhjho6Tc+hj507wTmzl6NLrTQfv6MooqtyuGC2mDOL7Nii4LcK2NJpLuHvUBKwrZ1pebbuCoGRw6IYsMHkCtA+fdZn71uSANA+iW+YJF1DngoABd15jmfZ5nc8OaKveri6E6FO80vFIOiZiaBECEHX5FaZNXzuvO+FB8TxxuBEOb+dY7Ixjp6o7RTUaN8Tvkasq6+yO3m/qZASlaWFot4/nUbQ4mrcFuNLwy+AwF+mWj2zs3gyLp1txyM/1d8iC9djwj2ij3+RvrWWTV3F9yfiD8zYm1kGdNYno/Tq0dwzn+evQoFt9B9kiABdcPUXmsEKvU7ANm5mqwujGSQkBqvjrTcuFqN1W8rB2Vt2lh8kORdOag0wokRqEIr9baRRmW1FMdW4R58MD3R++Lj8UGrp1MYp3/RgT408m2ECVAdf4WqslKYIYvuu8wd+RU4riEmViAqhOLUTpPSPaLtrM=</ds:X509Certificate></ds:X509Data><ds:KeyValue><ds:RSAKeyValue><ds:Modulus>mkUhqWAuhLDVm1aQpLxgeyo6ZezrJN5qyTQZFV9wHMzyL/cOL5HT8WCumxt8oTJlyNRJZCZ4clfvnPf2b/dnqS+SE0QWsA8WJJ5rMgaSJ0ndsVzzMtgsVhpeO5rP4ZFudRKrDlHzfwNP6tjpwZnWdjyBhMurVqg6v1bUb4ffTUJzCYp2flOFM2QvsDKH7yKNnU718PI34cp8dWgRWqbtv/fkIuFhSIU/rlKatfAhmmWnQQWkkms+G2ADM7BNFhG6899Oy9/BaEXjBUm8kn5KMh8ww5CN2RYZpNElGTMqt/mY+sAhUZOv6B3Ouvv+0qMBYc8teoQtxHHNl2UcbBmLyw==</ds:Modulus><ds:Exponent>AQAB</ds:Exponent></ds:RSAKeyValue></ds:KeyValue></ds:KeyInfo>`

This block is added programmatically before signing adding the PEM of the public chain certificates.. I've reviewed each chain and I don't see nothing wrong..

Any idea about any trick to solving this last (I hope!) error?

Many many thanks for your help!

**Comment by microshine** [comment]
Interesting. In my example, I update `KeyInfo` before signing, and it doesn't break the signature

Please double-check that you don't change `XmlSignature` object after signing

<img width="734" alt="image" src="https://user-images.githubusercontent.com/7333669/176425701-1006a24b-2a71-41f5-b096-71506122457c.png">

**Comment by microshine** [comment]
It's possible that `verify` changes incoming objects on processing. Please serialize your signed XML to string and parse it again for verify (like I do in my example)

About `xadesjs.com` I'm not sure if it uses the latest version of the lib. I need to check it out.

Try https://tools.chilkat.io/xmlDsigVerify for XML verification

**Comment by jsousa-Resulto** [comment]
<img width="1169" alt="image" src="https://user-images.githubusercontent.com/56820092/176443563-6d94c864-3e28-4140-9f78-a5ae912ac8e9.png">

Thanks a lot @microshine! Now I'm going to continue trying to send xml and asking why validator returns "The signing policy is not correct".

**Comment by jsousa-Resulto** [comment]
Hi!

it seems that the signature fails policy validations in most validators (in my code and in your example, is a general validation fail). For example at https://ec.europa.eu/digital-building-blocks/DSS/webapp-demo/validation

I've seen that is not accepted like XAdes-EPES, is recognized as XAdes-BES.. This clue is the one i'm following

I'm doing some research to try to identify where the problem is. You may have commented on it on occasion but I haven't seen anything in the repository. I will try to provide the information that I obtain.

Thanks!

**Comment by jsousa-Resulto** [comment]
We can close this issue. Finally, reviewing policy digest I get a valid xml. Thanks a lot for your help! Your sample code in https://codesandbox.io/s/issue-122-xfjb6v?file=/src/index.ts will be very great for a lot of colleagues. I'll recommend your solution!
