### ISSUE TITLE
<X509SerialNumber /> not an integer

### ISSUE THREAD

**Issue by moll** [PeculiarVentures/xadesjs#52]
Hey,

Just a heads up that I too stumbled upon an issue with certificate serial numbers getting serialized in hex where they should be integers and noticed there's even a related TODO line (https://github.com/PeculiarVentures/xadesjs/blob/master/src/signed_xml.ts#L141) about. Docs signed with certs with such serial numbers obviously fail to validate outside of Xades.js. :)

**Comment by moll** [comment]
Then again, this bug may be in Xmldsig.js. Not sure which bit does what here yet. ;)

**Comment by microshine** [comment]
@moll Thank you for your issue. I'm waiting for new update of [asn1.js](https://github.com/PeculiarVentures/asn1.js) which must allow to convert `INTEGER` values to BIG number. This update must resolve current problem

**Comment by moll** [comment]
Cool. Do you reckon there's any risk or unintended side-effect if I overwrite `Xmldsig.X509Certificate.SerialNumber` and have it return a string of a big number in the meanwhile?

**Comment by microshine** [comment]
I thought about `bn.js` module to fix this error. But developer of `asn1.js` told me that he support `INTEGER` conversion to BIG NUMBER in 1 or 2 days.
And you are right. We have to update `Xmldsig.X509Certificate.SerialNumber`. I don't see any risk of changing this. There can be also added converter for [SerialNumber](https://github.com/PeculiarVentures/xmldsigjs/blob/master/src/xml/key_infos/x509_data.ts#L40) attribute to check correct integer data.

**Comment by YuryStrozhevsky** [comment]
Now we the latest changes in ASN1.js and pvutils you would be able to get string representation like this:
```javascript
const serialNumberRepresentation = certificate.serialNumber.valueBlock.toString();
```

**Comment by microshine** [comment]
I published new versions of `xmldsigjs` and `xadesjs`. It returns `integer` in `<SerialNumber>`
@moll Could you check it?

**Comment by moll** [comment]
Will do. Thank you! Did you fix the dependency bugs in those two, too, that I reported in other issues?

**Comment by microshine** [comment]
no, I didn't

**Comment by moll** [comment]
However https://github.com/PeculiarVentures/xmldsigjs/commit/d9c2f90a12a6006443791756b1310949a97b97e0 seems to indicate you _did_ fix https://github.com/PeculiarVentures/xmldsigjs/issues/8. ;)

**Comment by moll** [comment]
Having said that, you're right, xml-core is still missing as per https://github.com/PeculiarVentures/xadesjs/issues/50.
